version: "3"

services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8001:9000
    volumes:
      - ./:/usr/src/app:ro
    #env_file:
      #- ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload

    environment:
      - DATABASE_NAME=postgresql+asyncpg://postgres:password123@postgres:5432/app-social
            
      - DATABASE_TEST_NAME=postgresql+asyncpg://postgres:password123@localhost:5432/app-social_test
      - ALGORITHM=HS256
      - SECRET_KEY=GHVJYGJBHLYVHHJKLGUKGYGLHVVJTCJTBKUBNJ
      - EXPIRY_TIME=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=app-social

    volumes:
      - postgres-db:/var/lib/postgresql/data 

volumes:
  postgres-db:



