"""post

Revision ID: 498a2d66c587
Revises: 4af98dd70e12
Create Date: 2023-03-28 11:59:21.495733

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '498a2d66c587'
down_revision = '4af98dd70e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
