"""post

Revision ID: 4af98dd70e12
Revises: 7f04c10cf609
Create Date: 2023-03-28 11:57:58.285809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4af98dd70e12'
down_revision = '7f04c10cf609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
