"""edit user table

Revision ID: 4d59763e7bff
Revises: 2a820fa498e6
Create Date: 2023-04-01 08:33:20.317001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4d59763e7bff'
down_revision = '2a820fa498e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirm_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
