"""users

Revision ID: 6d81a1a5210b
Revises: 60bb436ba05b
Create Date: 2023-04-01 07:32:32.148953

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6d81a1a5210b'
down_revision = '60bb436ba05b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
