"""owner_email

Revision ID: 707aa426c2ab
Revises: 4d59763e7bff
Create Date: 2023-04-04 15:32:17.511641

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '707aa426c2ab'
down_revision = '4d59763e7bff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
