"""owner_email

Revision ID: c1cf003add3e
Revises: 707aa426c2ab
Create Date: 2023-04-04 15:40:43.058730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c1cf003add3e'
down_revision = '707aa426c2ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
