name: Social App github action workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repository
        uses: actions/checkout@v2
      - name: set up python
        run: sudo apt install python3
      - name: python mode
        run: python3
      - name: print 
        run: print("hello")

        
       
