name: Social App github action workflow

on: [push]

jobs:

  job1:
    environment: delopment
    env:
      database_test_name: ${{secrets.database_test_name}}
      database_name: ${{secrets.database_name}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      EXPIRY_TIME: ${{secrets.EXPIRY_TIME}}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling repository
        uses: actions/checkout@v2
      - name: set up python
        run: sudo apt install python3
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest for testing
        run: pytest

        
       
