name: Social App github action workflow

on: [push]

jobs:

  job1:
    environment: development
    env:
      database_test_name: postgresql+asyncpg://postgres:password123@localhost:5432/app-social_test
      database_name: ${{secrets.database_name}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      EXPIRY_TIME: ${{secrets.EXPIRY_TIME}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling repository
        uses: actions/checkout@v2
      - name: set up python
        run: sudo apt install python3
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest for testing
        run: pytest

        
       
