name: Social App github action workflow

on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling repository
        uses: actions/checkout@v2
      - name: set up python
        run: sudo apt install python3
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest for testing
        run: pytest

        
       
